title: "My Blog Github"
author: "Your Name"
description: "Welcome to my blog"
url: ""
baseurl: ""
permalink: /:year/:month/:day/:title/
timezone: Asia/Ho_Chi_Minh
markdown: kramdown
highlighter: rouge
exclude: [README.md]
theme_config:
  brand_title: "My Blog Github"
  nav:
    - title: "ABOUT ME"
      url: "/about/"
    - title: "CONTACT"
      children:
        - title: "Email"
          url: "mailto:you@example.com"
        - title: "Facebook"
          url: "https://facebook.com/"
    - title: "RADIO LOFI CHILL"
      url: "https://www.youtube.com/watch?v=jfKfPfyJRdk"
    - title: "Curriculum Vitae"
      url: "/cv/"
